### ISSUE TITLE
Request of release new version for https://github.com/PR2/pr2_navigation/pull/18

### ISSUE THREAD

**Issue by garaemon** [PR2/pr2_navigation#19]
Please release new version for https://github.com/PR2/pr2_navigation/pull/18

**Comment by UltronDestroyer** [comment]
This has been released in Indigo.

**Comment by garaemon** [comment]
Could you release it on hydro too?

2015年6月15日月曜日、Devon Ashnotifications@github.comさんは書きました:

> This has been released in Indigo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PR2/pr2_navigation/issues/19#issuecomment-112069502.

## 

✉︎ from iPhone

**Comment by UltronDestroyer** [comment]
I'm not sure Hydro packages will be built anymore, can you confirm this for me?

**Comment by garaemon** [comment]
I believe shadow-fixed is still alive

**Comment by UltronDestroyer** [comment]
That's right. If you don't mind installing from shadow-fixed I'll re-release it.

**Comment by garaemon** [comment]
Please release to hydro shadow-fixed because we still using hydro.

BTW, have you confirmed PR2 software works on indigo?

**Comment by UltronDestroyer** [comment]
I ran PR2 navigation in Indigo simulation and it worked fine. I ran the code on the real robot with no bugs, but I haven't used it on the PR2 Indigo yet.

**Comment by UltronDestroyer** [comment]
Pending acceptance of https://github.com/ros/rosdistro/pull/8679 and then I will close this issue.

**Comment by furushchev** [comment]
@TheDash This is necessary to work move_base on PR2 real robot on hydro, could you release on hydro ASAP since hydro is almost EOL

**Comment by UltronDestroyer** [comment]
It was released 21 days ago. Where are you seeing that it's not?

**Comment by furushchev** [comment]
@TheDash I'm sorry for late response. Yes, I think this is not yet released on hydro. We still cannot locate `self_filter` node by `rosrun pr2_navigation_self_filter self_filter`.
Could you check from which version this feature is applied? Since there is no version tag on git.

Below is more detail information:

``` bash
$ sudo apt-get update
$ sudo apt-get install ros-hydro-pr2-navigation-self-filter
$ sudo apt-get upgrade
$ source /opt/ros/hydro/setup.bash
$ rospack find pr2_navigation_self_filter
/opt/ros/hydro/share/pr2_navigation_self_filter
$ rosversion pr2_navigation_self_filter
0.1.23
$ rosrun pr2_navigation_self_filter self_filter
[rosrun] Couldn't find executable named self_filter below /opt/ros/hydro/share/pr2_navigation_self_filter
```

**NOTE** When I use this repo with `hydro-devel`, I can locate `self_filter` node.

``` bash
$ roscd
$ catkin config
------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/hydro
Workspace:                   /home/furushchev/work/test_ws
Source Space:       [exists] /home/furushchev/work/test_ws/src
Build Space:        [exists] /home/furushchev/work/test_ws/build
Devel Space:        [exists] /home/furushchev/work/test_ws/devel
Install Space:      [exists] /home/furushchev/work/test_ws/install
DESTDIR:                     None
------------------------------------------------------------------
Isolate Develspaces:         False
Install Packages:            True
Isolate Installs:            False
------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------------
Workspace configuration appears valid.
------------------------------------------------------------------
$ cd src
$ wstool set pr2_navigation --git https://github.com/PR2/pr2_navigation.git -v hydro-devel
$ wstool up 
$ catkin config --install && catkin build pr2_navigation
$ source ../install/setup.bash
$ rospack find pr2_navigation_self_filter
/home/furushchev/work/test_ws/install/share/pr2_navigation_self_filter
$ rosversion pr2_navigation_self_filter
0.1.27
$ rosrun pr2_navigation_self_filter self_filter
[ WARN] [1437901362.234699996]: No links specified for self filtering.
[ WARN] [1437901362.255135753]: No robot links will be checked for self mask
# it works.
```

**Comment by TDiazT** [comment]
Hello, 

We've been encountering a similar issue as @furushchev where it cannot find the self_filter node in the pr2_navigation_self_filter package. This is on hydro.

The error we are encountering is this one, when doing `roslaunch pr2_2dnav pr2_2dnav.launch`:

![pr2_2dnaverrors](https://cloud.githubusercontent.com/assets/7966908/15653537/035b12c2-2664-11e6-959c-31984cfa439b.png)

The steps we followed to try and fix it were:
1. add package information to .rosinstall
   
   ```
   $ cd /path/to/your/catkin_ws
   $ wstool set pr2_navigation --git https://github.com/pr2/pr2_navigation -v 0.1.27 -t src
   $ wstool up pr2_navigation -t src
   ```
2. build packages
   
   `$ catkin build pr2_2dnav # or catkin_make`
3. launch again
   
   ```
   $ source devel/setup.bash
   $ roslaunch pr2_2dnav pr2_2dnav.launchh
   ```

When we run `catkin config` in the workspace it shows `/opt/ros/hydro` is in Extending. Also, `catkin build` works ok.

This solution worked in gazebo, but not in the actual PR2.

We've been stuck for a long time on this, could you give us any thoughts on this please?

**Comment by UltronDestroyer** [comment]
It looks like CMakeLists isn't installing self_filter. Quick fix.

**Comment by TDiazT** [comment]
Sorry, I couldn't quite understand, should I do something with the CMakelist?

**Comment by TDiazT** [comment]
@TheDash I'm sorry, I couldn't quite understand, should I do something with the CMakelist?

**Comment by UltronDestroyer** [comment]
Edit: my apologies there is no Indigo branch. I'll have a look at the install target locations for self_filter.

**Comment by UltronDestroyer** [comment]
I installed pr2_naviation and used hydro-devel, I compiled it and was able to find self_filter.  Note this was from source. If the error persists on the debs, that's quite unfortunate as I don't think there will be any more public releases. You will have to use it via shadow-fixed or by source.

**Comment by TDiazT** [comment]
@TheDash We managed to solve it, not sure if the best solution but it works. 

The self_filter node was being installed as well as semantic_point_annotator but when launching the file (pr2_2dnav) it kept looking in the wrong place for the executables. The solution we found was to create symlinks to the correct paths.

Thank you

**Comment by UltronDestroyer** [comment]
Do you know the path it was installed to? I'm assuming you fixed this via using the debs (since source code should've had this patched already)

Thanks for clarifying this for other users @TDiazT
