### ISSUE TITLE
Obstacles not being added in costmap in Indigo 

### ISSUE THREAD

**Issue by UltronDestroyer** [PR2/pr2_navigation#26]
Obstacles are not being added to the cost-map in ROS Indigo

In the images you can see obstacles from the tilt scanner are not being added to the local cost map (they are too high for the base scanner). In the video you can see the robot is not avoiding obstacles, or even properly following the global plan.

![costmap2](https://cloud.githubusercontent.com/assets/1786601/17778716/0250be46-6533-11e6-8fe3-2b074636cb70.png)
![costmap1](https://cloud.githubusercontent.com/assets/1786601/17778721/0440322c-6533-11e6-8483-77fba29743b5.png)

**Comment by DLu** [comment]
This is probably better handled on answers.ros.org, where we can get the link to the video and full configuration.

**Comment by UltronDestroyer** [comment]
Sounds good, i'll post it there.

**Comment by DLu** [comment]
(I just realized this wasn't the navigation repo...sorry for dictating what to do)
